styling of signup page updated
Praful932/Kitabe pull request #108
Opened 2021-03-17 06:10 UTC by Ankita297

## Description
- styling of signup and login page updated
- #50 

## Affected Dependencies
NA

## How has this been tested?
I have tested it in my local  system .

## GIF Before
NA
## GIF After
https://user-images.githubusercontent.com/67833077/111422686-10273500-8715-11eb-867a-86a7447d54d5.mp4

## Checklist
- [ x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [ x] My changes do not edit/add any unrequired files.
- [x ] My changes are covered by tests.

2021-03-18 06:32 UTC, maneprajakta requested changes
The hovering effect added doesn't seem good to me. Can you improve it?

2021-03-18 06:34 UTC, Ankita297 commented
@maneprajakta  should i remove it ?

2021-03-18 06:37 UTC, Ankita297 commented
or any other idea ?

2021-03-18 06:41 UTC, maneprajakta commented
> @maneprajakta should i remove it ?

Yep remove it.

2021-03-18 08:00 UTC, Ankita297 commented
Is it okay now @maneprajakta ?

2021-03-18 14:33 UTC, maneprajakta commented
> Is it okay now @maneprajakta ?

@Ankita297 the color doesn't go with our website theme.Try to match with it.

2021-03-18 14:39 UTC, Ankita297 commented
@maneprajakta  are you talking about form color . should i change it color to blue like in read genre wise section or any other idea from your side .

2021-03-18 14:47 UTC, maneprajakta commented
@Ankita297 
Keep it white, remove the grey color also decrease the space between sign in  and sign up button 
You can improve the button style their color any color which goes with the background.

2021-03-18 16:09 UTC, Ankita297 commented
![Sign Up - Google Chrome 18-03-2021 21_37_59](https://user-images.githubusercontent.com/67833077/111658405-57571800-8832-11eb-958e-ed64cb79de4c.png)
![Sign Up - Google Chrome 18-03-2021 21_38_06](https://user-images.githubusercontent.com/67833077/111658439-5cb46280-8832-11eb-9157-1671205f7bd8.png)

2021-03-18 16:10 UTC, Ankita297 commented
is it okay now @maneprajakta

2021-03-18 16:22 UTC, maneprajakta commented
> is it okay now @maneprajakta

Yep :100:

2021-03-18 16:41 UTC, Praful932 requested changes
@Ankita297 Add GIFS of UI in responsive mode in all sizes, check earlier page to see how it behaves with change in screen size

2021-03-18 17:54 UTC, Ankita297 commented
@Praful932 @maneprajakta  is it okay now ?

2021-03-18 18:00 UTC, maneprajakta commented
@Ankita297 you need to wait for a while we have PR #117 we need to merge that. The PR will add a button to a sign-up page.
After that, you need to update your fork do changes for that button only. We will let you know.

2021-03-19 18:50 UTC, Praful932 commented
@Ankita297 You can proceed to update your branch with the new changes, the required PR has been pushed

2021-03-20 02:46 UTC, Ankita297 commented
@Praful932 Done Sir .

2021-03-20 06:53 UTC, maneprajakta requested changes
@Ankita297 Could you place `Sign Up With Google` and `Sign In With Google`  both buttons inside the form border below sign-in button and keep its styling same as sign-in button .
For both pages do same.

2021-03-20 07:38 UTC, Ankita297 commented
![Sign Up - Google Chrome 20-03-2021 13_06_25](https://user-images.githubusercontent.com/67833077/111862742-2e8f6980-897d-11eb-906f-c8b9663d2aed.png)

2021-03-20 07:38 UTC, Ankita297 commented
@maneprajakta  is it okay ?

2021-03-20 12:15 UTC, Praful932 commented
> @Ankita297 Could you place `Sign Up With Google` and `Sign In With Google` both buttons inside the form border below sign-in button and keep its styling same as sign-in button .
> For both pages do same.

We merged that PR, @Ankita297 needs to update her branch,
@Ankita297 check the current latest [page](https://kitabe-app.herokuapp.com/accounts/login/), Also no need to call sir :)

2021-03-20 12:55 UTC, maneprajakta commented
> @maneprajakta is it okay ?

Yep :rocket:

2021-03-20 13:24 UTC, Ankita297 commented
@maneprajakta  Done.

2021-03-20 16:44 UTC, maneprajakta requested changes
- For small screen, it's messed up make it responsive
![Screenshot from 2021-03-20 22-09-09](https://user-images.githubusercontent.com/57425995/111877417-560c2380-89c9-11eb-845b-55a1ff34be59.png)
![Screenshot from 2021-03-20 22-08-48](https://user-images.githubusercontent.com/57425995/111877418-59071400-89c9-11eb-9043-c18fdad37424.png)

- For big screen bottom border of form is not there in Signup.html
![Screenshot from 2021-03-20 22-09-22](https://user-images.githubusercontent.com/57425995/111877448-74721f00-89c9-11eb-89ef-0cf7f20f58b8.png)

2021-03-20 16:44 UTC, maneprajakta commented on templates/account/login.html
> +                    <a href="{% provider_login_url 'google' %}"><button class="googlebutton">Sign In with Google</button></a>
the button doesn't work now

2021-03-20 16:44 UTC, maneprajakta commented on templates/account/signup.html
> +                    <a href="{% provider_login_url 'google' %}"><button class="googlebutton">Sign Up with Google</button></a>
The button doesn't work

2021-03-20 16:55 UTC, Ankita297 commented on templates/account/signup.html
> +                    <a href="{% provider_login_url 'google' %}"><button class="googlebutton">Sign Up with Google</button></a>
I will resolve it @maneprajakta

2021-03-21 15:43 UTC, Ankita297 commented
@maneprajakta  check it now .

2021-03-22 03:15 UTC, maneprajakta commented
@Ankita297 for small screen it's still messed up.

2021-03-22 03:16 UTC, maneprajakta commented
@Ankita297 for small screen it's messed up

2021-03-22 03:26 UTC, Ankita297 commented
![Login - Google Chrome 22-03-2021 08_54_36](https://user-images.githubusercontent.com/67833077/111936743-59e49680-8aec-11eb-86b9-4170313f28a8.png)

2021-03-22 03:49 UTC, maneprajakta commented
follow this 360X640 px

2021-03-22 03:49 UTC, Ankita297 commented
okay

2021-03-22 03:50 UTC, Ankita297 commented
![Login - Google Chrome 22-03-2021 09_20_03](https://user-images.githubusercontent.com/67833077/111938390-d9279980-8aef-11eb-9d25-bb6448cce26c.png)

2021-03-22 03:51 UTC, Ankita297 commented
like his @maneprajakta

2021-03-22 03:55 UTC, maneprajakta commented
@Ankita297 yep :+1:

2021-03-22 05:20 UTC, Praful932 requested changes
@Ankita297 Please see the deployment

2021-03-22 05:22 UTC, Praful932 requested changes
@Ankita297 Please see the deployment, make the `Welcome Back` smaller as in original and move the buttons down
![image](https://user-images.githubusercontent.com/45713796/111943942-8accc780-8afc-11eb-89f6-2f300124a3e7.png)

2021-03-22 05:24 UTC, Ankita297 commented
Sir which button should i move down ? Are you asking for sign up with google out of box

2021-03-22 05:24 UTC, Ankita297 commented
@Praful932

2021-03-22 05:28 UTC, Ankita297 commented
@Praful932  I have to make the font  of welcome smaller and then which button on which page ?

2021-03-22 14:23 UTC, Ankita297 commented
@maneprajakta  Please clear it out ?

2021-03-22 16:35 UTC, Praful932 commented
@maneprajakta Could you have a look at this, the deployement doesn't seem to match the provided ss

2021-03-22 16:38 UTC, Ankita297 commented
actually @Praful932 I have not udated the  previous gif Do i need to update it

2021-03-22 16:39 UTC, Praful932 commented
> actually @Praful932 I have not udated the previous gif Do i need to update it

yes

2021-03-22 16:42 UTC, Ankita297 commented
Okay @Praful932

2021-03-22 16:58 UTC, Ankita297 commented
@Praful932  is it okay now ?

2021-03-23 03:45 UTC, maneprajakta commented
@Ankita297 commit the changes done till now. We will directly check the deployed PR and let you know the necessary chnages.

2021-03-23 04:32 UTC, Ankita297 commented
@maneprajakta  I have commited all the changes till now

2021-03-23 11:12 UTC, maneprajakta requested changes
- Reduce the gap between buttons for both pages in both small & large screens. Marked below by blue. 
![Screenshot from 2021-03-23 16-36-42](https://user-images.githubusercontent.com/57425995/112137621-7c62d680-8bf6-11eb-8870-fa401cb13f2a.png)
- Also the border doesn't seem to be centrally aligned it's rightward shifted.

2021-03-23 15:27 UTC, Ankita297 commented
@maneprajakta   form-group is aligned properly . Please see .

2021-03-23 18:26 UTC, maneprajakta commented
Yep :+1:

2021-03-23 18:59 UTC, Praful932 requested changes
@Ankita297 It kinda is going out of the screen and also make the whole welcome header a bit smaller see the original page
![image](https://user-images.githubusercontent.com/45713796/112202876-e485dc80-8c37-11eb-934c-d8e71fc503fc.png)

2021-03-24 08:10 UTC, Ankita297 commented
@maneprajakta  please see

2021-03-24 18:14 UTC, Praful932 requested changes
Login seems different now, we need it a bit down, see the original page
![image](https://user-images.githubusercontent.com/45713796/112362737-c2a15e00-8cfa-11eb-8940-b8bc8c244c55.png)

2021-03-25 03:00 UTC, Ankita297 commented
Uploading final_605bfc5a40ffe00048a61f18_975245.mp4…

2021-03-25 03:01 UTC, Ankita297 commented
@maneprajakta  @Praful932  If it is okay from Your side then  i will commit the changes .

2021-03-25 03:02 UTC, Ankita297 commented
https://user-images.githubusercontent.com/67833077/112412465-8abf0880-8d44-11eb-96fc-185d75ea7bbd.mp4

2021-03-25 04:26 UTC, Praful932 commented
@Ankita297 Looks better now, you can push the new changes

2021-03-25 04:32 UTC, Ankita297 commented
@Praful932   Please review .

2021-03-25 04:37 UTC, Praful932 approved these changes

2021-03-25 04:39 UTC, Ankita297 commented
@maneprajakta Please review the changes .

2021-03-25 04:52 UTC, maneprajakta approved these changes
Great Work :rocket:

2021-03-25 04:55 UTC, Ankita297 commented
Thankyou @maneprajakta  @Praful932 .

2021-03-25 04:56 UTC, merged