Improved the book list layout of the explore page
Praful932/Kitabe pull request #120
Opened 2021-03-18 18:16 UTC by AmrutaKoshe

## Description
- Changed the layout of the explore page to make it user friendly. Made it similar to the layout of the book-genre page.
- made changes in the files explore.html and explore.css
- closes #74 

Before:
![image](https://user-images.githubusercontent.com/59871941/111675915-aa859680-8843-11eb-87ff-3056e2349295.png)

After:
![image](https://user-images.githubusercontent.com/59871941/111675941-b2ddd180-8843-11eb-9410-88ac61c6a81d.png)

on small screens:
![explorePagePhone](https://user-images.githubusercontent.com/59871941/111676321-0d772d80-8844-11eb-9e67-3171b9fa69ad.gif)

## Affected Dependencies

## How has this been tested?
Ran it in my localhost

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

2021-03-19 03:43 UTC, maneprajakta requested changes
- For large screens button seem to overlap
![Screenshot from 2021-03-19 09-09-09](https://user-images.githubusercontent.com/57425995/111728593-2f4bd100-8893-11eb-8b4d-1fd572286f44.png)
- For small screen content is not at center 
- Check this for small screen .
![Screenshot from 2021-03-19 09-10-50](https://user-images.githubusercontent.com/57425995/111728622-4094dd80-8893-11eb-9c42-443de7a8a901.png)

2021-03-19 06:50 UTC, AmrutaKoshe commented
> * For large screens button seem to overlap
>   ![Screenshot from 2021-03-19 09-09-09](https://user-images.githubusercontent.com/57425995/111728593-2f4bd100-8893-11eb-8b4d-1fd572286f44.png)
> * For small screen content is not at center
> * Check this for small screen .
>   ![Screenshot from 2021-03-19 09-10-50](https://user-images.githubusercontent.com/57425995/111728622-4094dd80-8893-11eb-9c42-443de7a8a901.png)



> * For large screens button seem to overlap
>   ![Screenshot from 2021-03-19 09-09-09](https://user-images.githubusercontent.com/57425995/111728593-2f4bd100-8893-11eb-8b4d-1fd572286f44.png)
> * For small screen content is not at center
> * Check this for small screen .
>   ![Screenshot from 2021-03-19 09-10-50](https://user-images.githubusercontent.com/57425995/111728622-4094dd80-8893-11eb-9c42-443de7a8a901.png)

I have solved all these issues. Please review ~

2021-03-19 10:13 UTC, maneprajakta commented
@AmrutaKoshe 
- Buttons still seem to overlap for large screens
- For small screen book card is not at the center now.

2021-03-19 10:54 UTC, maneprajakta commented
@AmrutaKoshe 
Still, it doesn't seem to work :
- Because the card is not at the center the carousel control for the right side is not visible properly.
![Screenshot from 2021-03-19 16-12-50](https://user-images.githubusercontent.com/57425995/111769389-309aef00-88cf-11eb-88b1-4c1129112d77.png)
- Button overlapping problem is solved but on hover, it persists. Move rate this button left side.
![k](https://user-images.githubusercontent.com/57425995/111769694-84a5d380-88cf-11eb-8c96-86a91328ed97.png)

2021-03-19 13:59 UTC, AmrutaKoshe commented
> @AmrutaKoshe
> Still, it doesn't seem to work :
> 
> * Because the card is not at the center the carousel control for the right side is not visible properly.
>   ![Screenshot from 2021-03-19 16-12-50](https://user-images.githubusercontent.com/57425995/111769389-309aef00-88cf-11eb-88b1-4c1129112d77.png)
> * Button overlapping problem is solved but on hover, it persists. Move rate this button left side.
>   ![k](https://user-images.githubusercontent.com/57425995/111769694-84a5d380-88cf-11eb-8c96-86a91328ed97.png)

Okay! I increased the gap between the buttons. 
For the cards in small screen, margin: auto doesn't work for some reason so I specified different margins with media queries. Does it look proper now?

2021-03-19 15:18 UTC, Praful932 commented
Hi @AmrutaKoshe , you can check out the changes in the temp deploy :)
https://kitabe-pipeline-pr-120.herokuapp.com/

2021-03-19 15:28 UTC, AmrutaKoshe commented
> Hi @AmrutaKoshe , you can check out the changes in the temp deploy :)
> https://kitabe-pipeline-pr-120.herokuapp.com/

Yes! I have been checking that 😁 
And it looks fine on my device

2021-03-19 16:58 UTC, maneprajakta requested changes
For large screen, if you could add bottom padding to the author name so that it doesn't collide with the buttons.
![Screenshot from 2021-03-19 22-17-01](https://user-images.githubusercontent.com/57425995/111815971-483f9b00-8902-11eb-823f-57724ab1b26d.png)

2021-03-19 16:58 UTC, maneprajakta commented on static/mainapp/css/explore.css
> +    margin-left: -0.5%;
-1.5% works for aligning center

2021-03-19 16:58 UTC, maneprajakta commented on static/mainapp/css/explore.css
> +@media (max-width: 370px){
This query will not work as already 370px query is there

2021-03-19 17:38 UTC, AmrutaKoshe commented
> For large screen, if you could add bottom padding to the author name so that it doesn't collide with the buttons.
> ![Screenshot from 2021-03-19 22-17-01](https://user-images.githubusercontent.com/57425995/111815971-483f9b00-8902-11eb-823f-57724ab1b26d.png)

Okay! changed it to -1.5%
Also, the space between author name and buttons depends on how big the name of book & author is -
![image](https://user-images.githubusercontent.com/59871941/111820883-0580c180-8908-11eb-8538-fbacec2d4e0f.png)

So I think a different issue can be created to resolve this problem !

2021-03-20 06:38 UTC, maneprajakta approved these changes

2021-03-20 06:39 UTC, maneprajakta commented
@AmrutaKoshe Great  Work :rocket: 
Yep, a new issue needs to be created for that.

2021-03-20 12:21 UTC, Praful932 approved these changes
@AmrutaKoshe Lgtm, Impressive work 💯

2021-03-20 12:22 UTC, merged