Fix bug and enhance Genre section UI (issue#62)
Praful932/Kitabe pull request #150
Opened 2021-03-28 10:06 UTC by Greeshma2903

## Description
- Changed Genres carousel to multi-image form, for better UX
- Enhanced UI
- https://github.com/Praful932/Kitabe/issues/62#issue-828858522

## Affected Dependencies

## How has this been tested?
Using `flake8`, `python manage.py test`.
No test fails.

## GIF Before
- For large screens:
![Genre section- before-large screen](https://user-images.githubusercontent.com/70336930/112748225-05538680-8fd8-11eb-8590-c67391f00087.gif)
- For small screens:
![Genre-SmallScreen-before](https://user-images.githubusercontent.com/70336930/112748238-1dc3a100-8fd8-11eb-8e31-f872ddec4071.gif)

## GIF After
-For large screens:
![Genre-LargeScreen-after](https://user-images.githubusercontent.com/70336930/112748572-23ba8180-8fda-11eb-8fdf-fd058f7791f3.gif)
- For small screens:
![Genre-SmallScreen-After(1)](https://user-images.githubusercontent.com/70336930/112748703-24074c80-8fdb-11eb-8ce9-a97cabe727c6.gif)

## Checklist
- [✔ ] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [ ✔ ] My changes do not edit/add any unrequired files.
- [✔  ] My changes are covered by tests.

2021-03-28 12:04 UTC, maneprajakta requested changes
- Also for small screen the controllers at center would be much better like we have for `popular among users section`

2021-03-28 12:04 UTC, maneprajakta commented on templates/mainapp/index.html
> +    /* 3 carousel --
Remove this commented part for carousel 3,4,5

2021-03-28 12:48 UTC, Greeshma2903 commented
> * Also for small screen the controllers at center would be much better like we have for `popular among users section`

Okay, will work on it.

2021-03-28 16:40 UTC, maneprajakta approved these changes

2021-03-29 03:47 UTC, Praful932 approved these changes
@Greeshma2903 Nice Work 🚀

2021-03-29 03:48 UTC, merged

2021-03-29 07:25 UTC, Greeshma2903 commented
> @Greeshma2903 Nice Work 🚀

Thank you so much😊