Improve UI of Book Card
Praful932/Kitabe pull request #156
Opened 2021-03-29 10:51 UTC by Sonaljain6431

## Description
- Reduced the amount of text to be displayed on each book tile
- #148 

## Affected Dependencies
N/A

## How has this been tested?
Using flake8, python manage.py test.
No test fails.

## GIF Before
![screentogif_before](https://user-images.githubusercontent.com/52230497/112826310-72375100-90aa-11eb-8f93-258d33462016.gif)

## GIF After
![screentogif_after](https://user-images.githubusercontent.com/52230497/112826330-782d3200-90aa-11eb-9243-7c1c67996ab1.gif)

## Checklist
- [✓ ] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [✓ ] My changes do not edit/add any unrequired files.
- [✓ ] My changes are covered by tests.

2021-03-30 03:15 UTC, maneprajakta commented
@Sonaljain6431 [Unstage](https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request) settings.py

2021-03-30 04:42 UTC, Praful932 requested changes
You need to unstage `settings.py` so we can review

2021-03-30 05:39 UTC, Sonaljain6431 commented
Ok

2021-03-30 15:22 UTC, Sonaljain6431 commented
Is it ok now?

2021-03-30 16:30 UTC, Praful932 commented
LGTM, @Sonaljain6431 
We can add a issue for tooltip for all the book names and author title wdyt @maneprajakta

2021-03-31 03:15 UTC, maneprajakta approved these changes
Great work :rocket:

2021-03-31 03:18 UTC, maneprajakta commented
> LGTM, @Sonaljain6431
> We can add a issue for tooltip for all the book names and author title wdyt @maneprajakta or maybe this can be taken by the same PR since it's Level 2

@Praful932 
Yes we can it will help for getting complete title of book and author name.
I think we should go for another issue for this one.

2021-03-31 08:31 UTC, Sonaljain6431 commented
Do I need to make more changes?

2021-03-31 15:26 UTC, Praful932 commented
> Do I need to make more changes?

Nope, we can merge this :)

2021-03-31 15:27 UTC, Praful932 approved these changes

2021-03-31 15:27 UTC, merged