explore page layout changed
Praful932/Kitabe pull request #20
Opened 2020-12-19 05:26 UTC by maneprajakta

Will Fixe 1st sub-issue of issue #19 
Explore page in large screen will show books in the grid while for the small screen it will be in the carousel.

2020-12-20 17:31 UTC, Praful932 requested changes
Could you add sample ss?

2020-12-21 03:55 UTC, maneprajakta commented
SS for same:
Large screen:
![Screenshot from 2020-12-21 09-22-20](https://user-images.githubusercontent.com/57425995/102737809-67b04180-436e-11eb-9384-d4f24edc3895.png)
Mobile view:
![Screenshot from 2020-12-21 09-22-48](https://user-images.githubusercontent.com/57425995/102737824-6da62280-436e-11eb-806c-3d5ad95719e4.png)

2020-12-21 04:05 UTC, Praful932 commented
Looks Great!

2020-12-21 04:05 UTC, Praful932 approved these changes

2020-12-21 07:40 UTC, merged