Solved Frontend Bug Fixes #30
Praful932/Kitabe pull request #209
Opened 2021-04-22 06:48 UTC by reshchat

Fixes issue #30 with following changes :
Changed the size and alignment of rating buttons on Homepage
Changed the size and alignment of rating and "more details" buttons on Your read section

## Affected Dependencies

## How has this been tested?

Tested using flake8, python manage.py test

## GIF Before
- If any UI Changes, Use [this](https://www.screentogif.com/) to record or else specify NA

## GIF After

## Checklist
- [ ✓ ] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [ ✓ ] My changes do not edit/add any unrequired files.
- [ ✓ ] My changes are covered by tests.

![CPT2104221205-1399x519](https://user-images.githubusercontent.com/55682533/115667135-1c7d5e00-a363-11eb-8b61-a8972023d4ed.gif)
![CPT2104221211-1491x400](https://user-images.githubusercontent.com/55682533/115667871-f906e300-a363-11eb-96ff-cdb38d408162.gif)

2021-04-23 02:00 UTC, maneprajakta requested changes
- Explore page buttons should be aligned like this vertically not side by side.
![Screenshot from 2021-04-23 07-24-50](https://user-images.githubusercontent.com/57425995/115806957-5606a580-a405-11eb-8960-721a46afba9f.png)
- Validation is not added to `rate this book` button on your read page check home page `rate this book` button for that. 
![Screenshot from 2021-04-23 07-25-41](https://user-images.githubusercontent.com/57425995/115806964-5868ff80-a405-11eb-887d-242dfb78c895.png)

2021-04-23 04:39 UTC, reshchat commented
> * Explore page buttons should be aligned like this vertically not side by side.
>   ![Screenshot from 2021-04-23 07-24-50](https://user-images.githubusercontent.com/57425995/115806957-5606a580-a405-11eb-8960-721a46afba9f.png)
> * Validation is not added to `rate this book` button on your read page check home page `rate this book` button for that.
>   ![Screenshot from 2021-04-23 07-25-41](https://user-images.githubusercontent.com/57425995/115806964-5868ff80-a405-11eb-887d-242dfb78c895.png)

@maneprajakta can you please explain what is "validation" here .

2021-04-23 06:40 UTC, maneprajakta commented
Yep
So when I rate a book through  `rate this book` button its color should change like gif below for Your Read page.
![bug2](https://user-images.githubusercontent.com/57425995/115826372-709e4600-a428-11eb-8af5-5453706bc26d.gif)

2021-04-23 09:19 UTC, reshchat commented
@maneprajakta I've made the necessary changes. Please check

2021-04-23 10:51 UTC, maneprajakta reviewed
- This is what we need `margin-right: -12px;` works 
![Screenshot from 2021-04-23 16-17-14](https://user-images.githubusercontent.com/57425995/115860756-97bc3e00-a44f-11eb-9da6-7128a3a590ae.png)

2021-04-23 11:30 UTC, reshchat commented
@maneprajakta please check

2021-04-23 12:30 UTC, maneprajakta commented
@reshchat could you check [deployment](https://kitabe-pr-209.herokuapp.com/book_recommendations/) of your PR.
Adding only `margin-right: -12px;` on `more-details` class would have worked now it seems messed up.
If it's right at your side you can add ss of the recommendation page.

2021-04-23 12:40 UTC, reshchat commented
![Capture](https://user-images.githubusercontent.com/55682533/115872001-e6250900-a45e-11eb-8ba8-8ef1d31664c3.PNG)
Screenshot of the recommendation page.

Should I remove the margin-right: -12px; part from the rating-block
@maneprajakta

2021-04-23 12:55 UTC, reshchat commented
@maneprajakta 
I've made some changes. Can you check it again

2021-04-23 13:21 UTC, maneprajakta commented
> @maneprajakta
> I've made some changes. Can you check it again

@reshchat check is your screen resolution 1366 * 768.
I will put the changes in this https://github.com/Praful932/Kitabe/pull/209/commits/e3fee4fdfdfe2bf3f8c23f01f1b2ebf9aff37621 as the recent commit while be disturbing the page view on small screen.

2021-04-23 13:23 UTC, maneprajakta commented on static/mainapp/css/recommendation.css
> +  margin-right: -12px;
remove this

2021-04-23 13:23 UTC, maneprajakta commented on static/mainapp/css/recommendation.css
> +  left: 45%;
Keep it same as early 50%

2021-04-23 13:24 UTC, maneprajakta commented on static/mainapp/css/recommendation.css
> +  right: 34%;
keep same as before 26%

2021-04-23 13:59 UTC, reshchat commented
@maneprajakta I've made the changes

2021-04-23 18:22 UTC, maneprajakta approved these changes
LGTM :rocket:

2021-04-24 04:32 UTC, Praful932 approved these changes
LGTM!

2021-04-24 04:32 UTC, merged