Navbrand
Praful932/Kitabe pull request #61
Opened 2021-03-10 19:29 UTC by SandeepKrSuman

## Description
- Changes : (i) Added an image tag under nav tag inside ./templates/mainapp/layout.html (ii) Added a .png image inside ./static/mainapp/png which is same as the logo image but with the white background removed.
- closes #58 

## Affected Dependencies
No dependencies have been affected. Only a png image is added inside ./static/mainapp/png

## How has this been tested?
Tested locally for responsiveness.

## GIF Before
![before](https://user-images.githubusercontent.com/54541515/110685168-0167ec00-8204-11eb-86b0-c180b490fef6.gif)

## GIF After
![after](https://user-images.githubusercontent.com/54541515/110685223-0c228100-8204-11eb-9a11-4fa560eadc8e.gif)

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

2021-03-11 15:22 UTC, maneprajakta reviewed
@SandeepKrSuman rest all seems great :rocket:

2021-03-11 15:22 UTC, maneprajakta commented on templates/mainapp/layout.html
> +                <a class="navbar-brand head-text" href="/"><img width="200px" src="./static/mainapp/png/brand-img.png"></a>
Change the src to [this way](https://github.com/Praful932/Kitabe/blob/91c168d1bcd5888c835fc48bf3ff3e0ac05064b7/templates/mainapp/index.html#L19)  it is the way to specify the path of the static way in Django template.

2021-03-11 15:22 UTC, maneprajakta commented on templates/mainapp/layout.html
> +                <a class="navbar-brand head-text" href="/"><img width="200px" src="./static/mainapp/png/brand-img.png"></a>
The width seems more to me from screenshots reduce it a bit.

2021-03-11 16:30 UTC, maneprajakta approved these changes
Good to go :rocket:

2021-03-11 18:34 UTC, Praful932 requested changes
@SandeepKrSuman Could you update the GIFs with the latest GIFs also in responsive modes

2021-03-11 19:28 UTC, SandeepKrSuman commented
> @SandeepKrSuman Could you update the GIFs with the latest GIFs also in responsive modes


![ezgif com-gif-maker](https://user-images.githubusercontent.com/54541515/110843132-fa0d1500-82cd-11eb-879e-28acb662d441.gif)

2021-03-12 04:27 UTC, maneprajakta commented
> > @SandeepKrSuman Could you update the GIFs with the latest GIFs also in responsive modes
> 
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/54541515/110843132-fa0d1500-82cd-11eb-879e-28acb662d441.gif)

@SandeepKrSuman we have deployed your PR which you can visit [here](https://kitabe-pipeline-pr-61.herokuapp.com/)  it doesn't seem responsive for the small screen. Just check once from your end am I wrong. 
ss :
![Screenshot from 2021-03-12 09-54-41](https://user-images.githubusercontent.com/57425995/110891943-18e4c900-8319-11eb-8aa3-7cf13e429490.png)


Also, you are supposed to update the ss in the PR template [this one](https://github.com/Praful932/Kitabe/pull/61#issue-590063183) edit it.

2021-03-12 08:03 UTC, SandeepKrSuman commented
@maneprajakta I have made some changes for responsiveness in smaller devices. Added media query or the image width. 

Now it should be fine. 

Take a look: 
![Screenshot (243)](https://user-images.githubusercontent.com/54541515/110910518-75ef7780-8337-11eb-9034-8a466fa79677.png)

2021-03-12 14:03 UTC, maneprajakta requested changes
image width issue not of appropriate size.

2021-03-12 14:03 UTC, maneprajakta commented on static/mainapp/css/layout.css
> +  width: 100px;
The width of approx 130px suits better for this, the logo is appearing too small in large screen mode.

2021-03-12 14:03 UTC, maneprajakta commented on static/mainapp/css/layout.css
> +    width: 50px;
Choose a width size appearing too small in small screen mode.

2021-03-12 14:03 UTC, maneprajakta commented on templates/mainapp/layout.html
> +                <a class="navbar-brand head-text" href="/"><img class="navbrandimg" src="{% static 'mainapp/png/brand-img.png' %}"></a>
As the head-text class is not needed now remove it and also associated CSS with it.

2021-03-12 20:04 UTC, SandeepKrSuman commented
Please view the deployment on physical smaller-device(phone) too. Now it seems completely fine to me.

2021-03-13 03:30 UTC, maneprajakta approved these changes
Everything seems great to me.

2021-03-13 05:55 UTC, Praful932 requested changes
Great job so far @SandeepKrSuman.
[Your changes](https://kitabe-pipeline-pr-61.herokuapp.com/). [Master branch](https://kitabe-app.herokuapp.com/).
If you could see the the navbar height in both of them, the one in yours is a bit wider, if you could make the changes to reduce it to be of same size by making the kitabe icon a bit smaller so both of the navbars have the same even after icon is changed on all devices.
After that I would be happy to merge :) 

Here's an image for your reference
![image](https://user-images.githubusercontent.com/45713796/111020860-c07ffb00-83ee-11eb-8688-ead6a53ee6e2.png)

2021-03-13 06:48 UTC, SandeepKrSuman commented
hey @Praful932 , I have adjusted the size of kitabe icon and now the height of navbar seems similar in both master and this branch. Please have a look.

2021-03-13 13:21 UTC, Praful932 approved these changes

2021-03-13 13:22 UTC, Praful932 commented
Fantastic work LGTM @SandeepKrSuman 🚀
I'll merge this as soon as it is approved!

2021-03-13 13:29 UTC, maneprajakta approved these changes
Perfect image width.
Good to go :rocket: .

2021-03-13 13:33 UTC, SandeepKrSuman commented
Thankyou so much. 
Great that you guys were constantly guiding. Hope that this little contribution will add something to the project. Thanks a lot 😊

2021-03-13 13:38 UTC, merged