Added top button to index.html and explore.html.
Praful932/Kitabe pull request #66
Opened 2021-03-11 16:50 UTC by kanishka8276

## Description
- List out your changes
- I  have added a top button to ndex.html and explore.html. It is in the bottom right corner and will take the user to the top op the page.
- Link the Issue which this resolves
- #63 

## Checklist
- [ x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [ x] My changes do not edit/add any unrequired files.
- [ x] My changes are covered by tests.
-
Top button
![Screenshot (56)](https://user-images.githubusercontent.com/66053534/110823163-d3dc7a80-82b7-11eb-83f8-517758919768.png)
Top button when hover
![Screenshot (57)](https://user-images.githubusercontent.com/66053534/110823190-db038880-82b7-11eb-8f2b-dd99dd26cc22.png)

2021-03-12 04:17 UTC, maneprajakta commented
The issue seems valid to me.
@kanishka8276 why did you closed the issue 🙂 ? If you don't want to work on this let us know. We will assign someone else.

2021-03-12 04:29 UTC, kanishka8276 commented
Sorry but I didn't closed the issue. I closed the PR . Because it was blocked from merging. So, I thought of making the required changes and then make another PR. I am still working on it.

2021-03-12 04:35 UTC, Praful932 commented
Hi @kanishka8276, it's fine you can unstage that file without closing PR, follow steps [here](https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request). Also Update the PR description with relevant details & GIFs

2021-03-12 04:36 UTC, maneprajakta commented
> Sorry @maneprajakta but I didn't closed the issue. I closed the PR . Because it was blocked from merging as some checks were not passed. So, I thought of making the required changes and then make another PR. I am still working on it.

No problem 

> Sorry @maneprajakta but I didn't closed the issue. I closed the PR . Because it was blocked from merging as some checks were not passed. So, I thought of making the required changes and then make another PR. I am still working on it.

No issue you need to remove localhost from allowed host and also secret key it was before then PR will pass all checks.
You can make a fresh branch and do changes to it and make another PR :rocket: .

2021-03-12 04:39 UTC, kanishka8276 commented
Ok! Thank you.

2021-03-12 05:18 UTC, kanishka8276 commented
@Praful932  and @maneprajakta  please review this PR. I have made all the required changes. Sorry,I couldn't unstage settings.py using the command you suggested. It wasn't working for me.

2021-03-13 06:23 UTC, Praful932 commented
> Update the PR description with relevant details & GIFs

@kanishka8276 
Btw the `settings.py` got unstaged :)

2021-03-13 06:28 UTC, kanishka8276 commented
> > Update the PR description with relevant details & GIFs
> 
> @kanishka8276
> Btw the `settings.py` got unstaged :)

Oh! . The PR description contains the current images of the top button. And after that I just added html scrollbar behaviour property. Rest is the Same. What changes shall I make in the PR comment?

2021-03-13 06:30 UTC, Praful932 commented
> > > Update the PR description with relevant details & GIFs
> > 
> > 
> > @kanishka8276
> > Btw the `settings.py` got unstaged :)
> 
> Oh! . The PR description contains the current images of the top button. And after that I just added html scrollbar behaviour property. Rest is the Same. What changes shall I make in the PR comment?

Record GIFs and update it in the description

2021-03-13 12:35 UTC, kanishka8276 commented
@maneprajakta @Praful932 I will have to make changes in this. Actually previously I tested the code for the button only by creating a testing   HTML file because I was unable to setup the project. Now I have set it up and found that  the top button is not visible.
I have tried increasing the z-index and changing html.onscroll to body.onscroll but still it is not visible.
Can you please suggest me some changes.
I am trying my best and will try to do it as soon as possible. Sorry, for the delay.

2021-03-13 13:03 UTC, maneprajakta requested changes
@kanishka8276 Take your time, go through templates to see how they are inherited. Avoid repetition as much as possible. Also make sure you five appropriate id to button and names to function.

2021-03-13 13:03 UTC, maneprajakta commented on templates/mainapp/explore.html
> +	<script>
You can add this script here in [*layout.html*](https://github.com/Praful932/Kitabe/blob/91c168d1bcd5888c835fc48bf3ff3e0ac05064b7/templates/mainapp/layout.html#L357) this reduces repetition of code.

2021-03-13 13:03 UTC, maneprajakta commented on templates/mainapp/index.html
> +	<script>
If you put the script  in layout.html there will be no need for this

2021-03-13 13:06 UTC, kanishka8276 commented
@maneprajakta ok! I Will do that. Thank you for the help!😀

2021-03-13 13:24 UTC, Praful932 commented
@kanishka8276 I have only seen the top button you attached in the image, would suggest to keep it consistent with the project theme

2021-03-13 13:25 UTC, kanishka8276 commented
Ok!

2021-03-13 18:38 UTC, kanishka8276 commented
@Praful932 and @maneprajakta  .
Please review PR #88
I have tried to make the top button according to the theme of the page but if you want any colour changes please suggest

2021-03-14 05:54 UTC, closed without merging