Rate Stars from Search Modal
Praful932/Kitabe pull request #69
Opened 2021-03-12 08:32 UTC by sk1122

## Description
I have changed the way stars were displayed in Modal, Now each star has its own id and is a button, they are wrapped in form tag, whenever submits the star button, an AJAX Request is initiated and bookrating is changed in db, default rating is from csv file. 

## Affected Dependencies
No Dependencies is affected

## How has this been tested?
Django Tests have run and unit tests of Github Workflow also passes

## GIF Before
- If any UI Changes, Use [this](https://www.screentogif.com/) to record or else specify NA
- 

## GIF After

https://user-images.githubusercontent.com/40713709/110913799-95889f00-833b-11eb-8238-26d58f267ab7.mp4

## Checklist
- [ *] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [ *] My changes do not edit/add any unrequired files.
- [ *] My changes are covered by tests.

2021-03-13 06:09 UTC, Praful932 commented
@sk1122 Btw the commit history seems weird to me, are you using codespaces? I would suggest to name the commits according to the changes that you're making :)

2021-03-13 06:14 UTC, sk1122 commented
No, it was a issue which I was facing with git, so it is showing some weird git commit history

2021-03-13 06:25 UTC, Praful932 reviewed
> No, it was a issue which I was facing with git, so it is showing some weird git commit history

What IDE are you using?

2021-03-13 06:25 UTC, Praful932 commented on BookRecSystem/settings.py
> -SECRET_KEY = os.environ.get('KITABE_SECRET_KEY')
Please unstage this file from PR

2021-03-13 06:25 UTC, Praful932 commented on mainapp/views_ajax.py
> +            print(rating_object)
Please remove debugging statements :) from PR

2021-03-13 06:25 UTC, Praful932 commented on static/mainapp/css/layout.css
> +<<<<<<< HEAD
There's a conflict here?

2021-03-13 06:25 UTC, Praful932 commented on templates/mainapp/layout.html
> +                                    <button type="submit" class="fa fa-star star-btn" id="first"></button>
Hi, this is a nice implementation of yours for rating, though I would recommend to reuse the implementation in [layout.html](https://github.com/Praful932/Kitabe/blob/master/templates/mainapp/layout.html#L271) :)

2021-03-13 09:28 UTC, sk1122 commented
I have changed all files but they keep appearing when committing. 
I unstaged settings.py using
`git reset BookRecSystem/settings.py
`

But the problem persists when I committed again.

2021-03-13 09:29 UTC, sk1122 commented
I think it is fine now

2021-03-13 13:18 UTC, Praful932 commented
@sk1122 Could you [unstage ](https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request)all not required files from PR, Then I can review

2021-03-14 05:39 UTC, Praful932 requested changes
@sk1122 Could you [unstage ](https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request)all not required files from PR, Then I can review

2021-03-14 06:12 UTC, sk1122 commented
I will do it

2021-03-16 05:27 UTC, Praful932 commented
@sk1122 Any updates?

2021-03-16 06:44 UTC, sk1122 commented
I had committed yesterday, but it was creating conflict in layout.html,

I had unstaged all nit required files but conflict happened. @Praful932

2021-03-16 17:53 UTC, Praful932 commented
@sk1122 The issue seems to persist, could you open a new PR branching off master, if this is persisting

2021-03-16 18:09 UTC, sk1122 commented
Ok

2021-03-16 18:09 UTC, closed without merging