Added home button in the nav bar
Praful932/Kitabe pull request #97
Opened 2021-03-14 15:00 UTC by kanishka8276

## Description
- List out your changes
- I have added a home button to go to the index.html in the nav bar. I have kept it consistent with the theme.
- Link the Issue which this resolves
- #80 
## How has this been tested?
I have ran it in my localhost .

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [x] My changes do not edit/add any unrequired files.
- [x] My changes are covered by tests.

![Screenshot (71)](https://user-images.githubusercontent.com/66053534/111073228-f531a680-8503-11eb-82ea-65f91267db51.png)
![Screenshot (72)](https://user-images.githubusercontent.com/66053534/111073241-04b0ef80-8504-11eb-9ddc-bd313b5f518f.png)

2021-03-14 15:14 UTC, Praful932 requested changes
Update PR with SS/GIFs in responsive modes

2021-03-14 15:30 UTC, kanishka8276 commented
@Praful932 done!

2021-03-14 15:38 UTC, Praful932 requested changes

2021-03-14 15:38 UTC, Praful932 commented on templates/mainapp/layout.html
> -                <a class="navbar-brand" href="/"><img class="navbrandimg" src="{% static 'mainapp/png/brand-img.png' %}"></a>
You are overiding master branch here..

2021-03-14 16:18 UTC, kanishka8276 commented
@Praful932 done!

2021-03-14 19:57 UTC, Praful932 commented
@kanishka8276 There are still conflicts here.. Please resolve them

2021-03-15 03:18 UTC, kanishka8276 commented
Ok!

2021-03-15 04:16 UTC, kanishka8276 commented
@Praful932 done!

2021-03-15 08:35 UTC, maneprajakta commented
@kanishka8276 Have you tested it locally.
This is what we can see after deploying  [here](https://kitabe-pipeline-pr-97.herokuapp.com/)
Check once.

![Screenshot from 2021-03-15 14-01-11](https://user-images.githubusercontent.com/57425995/111125081-3921bb80-8597-11eb-9252-c9968c4ad91e.png)

2021-03-15 08:39 UTC, kanishka8276 commented
@maneprajakta  That's because layout.css is not committed which contained the styling for the top button.

2021-03-15 11:00 UTC, kanishka8276 commented
@Praful932 @maneprajakta  Done!
Deployment looks fine now!

2021-03-15 13:36 UTC, Praful932 requested changes
@kanishka8276 There are a lot of extra commits coming in your PR because your fork seems to be behind master
![image](https://user-images.githubusercontent.com/45713796/111161738-78fd9880-85c1-11eb-9f02-8b2899ca8bac.png)

2021-03-15 13:38 UTC, kanishka8276 commented
Yes, It is behind the master. But through upriver it's not updating . I tried many times.

2021-03-15 13:50 UTC, kanishka8276 commented
I have updated my fork. Now what should I do?

2021-03-15 13:51 UTC, kanishka8276 commented
> @kanishka8276 There are a lot of extra commits coming in your PR because your fork seems to be behind master
> ![image](https://user-images.githubusercontent.com/45713796/111161738-78fd9880-85c1-11eb-9f02-8b2899ca8bac.png)

@Praful932  I have updated my fork. Now, what should I do?

2021-03-15 18:14 UTC, Praful932 commented
@kanishka8276 You need to either rebase/merge with master from your fork, there's a lot of extra commits coming in..

2021-03-15 18:16 UTC, kanishka8276 commented
> @kanishka8276 You need to either rebase/merge with master from your fork, there's a lot of extra commits coming in..

Shall I make a new branch after pulling again from the fork and make changes.

2021-03-15 18:19 UTC, Praful932 commented
> > @kanishka8276 You need to either rebase/merge with master from your fork, there's a lot of extra commits coming in..
> 
> Shall I make a PR from a new branch after pulling again from the fork and make changes.

That works, close the PR, and make a new branch from master

2021-03-16 07:31 UTC, kanishka8276 commented
@Praful932  I have made another PR
#102 
Please review it.
And it's a humble request please deploy it .
I haven't uploaded the ss but I think the code should work fine
I have edited the file in the browser itself because through git it was including all the extra commits as well, I used the git pull command after updating the fork. But it didn't work.

2021-03-16 07:35 UTC, closed without merging